- name: "Install sysfsutils"
  hosts: 172.31.83.226
  become: true
  tasks:
    - name: "Check sysfsutils present or not"
      dnf:
        name: sysfsutils
        state: present
      register: x

    - name: "Install sysfsutils if not present"
      dnf:
        name: sysfsutils
        state: present
      when: x is failed

#    - name: "Start sysfsutils service"
#      systemd:
#        name: sysfsutils
#        enabled: yes


