- name: "Install terraform"
  hosts: localhost
  connection: local
  become: true
  tasks:

    - name: "Download Terraform repo"
      get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/terraform.repo
      register: x

    - name: "Confirm repo is sucessful or not"
      debug:
        msg: "Copied successful"
      when x: is succeeded


    - name: "Install terraform"
      dnf:
        name: terraform
        state: present

    - name: "Terraform installed"
      debug:
        msg: "Terraform Installed"



#    - name: "Start sysfsutils service"
#      systemd:
#        name: sysfsutils
#        enabled: yes


